export const US_AREA_CODES = [
    { code: '201', region: 'New Jersey (Jersey City, Hackensack)' },
    { code: '202', region: 'District of Columbia (Whole District)' },
    { code: '203', region: 'Connecticut (Bridgeport, New Haven)' },
    { code: '205', region: 'Alabama (Birmingham, Tuscaloosa)' },
    { code: '206', region: 'Washington (Seattle, Bainbridge Island)' },
    { code: '207', region: 'Maine (Whole State)' },
    { code: '208', region: 'Idaho (Whole State)' },
    { code: '209', region: 'California (Stockton, Modesto)' },
    { code: '210', region: 'Texas (San Antonio)' },
    { code: '212', region: 'New York (New York City - Manhattan)' },
    { code: '213', region: 'California (Los Angeles)' },
    { code: '214', region: 'Texas (Dallas)' },
    { code: '215', region: 'Pennsylvania (Philadelphia)' },
    { code: '216', region: 'Ohio (Cleveland)' },
    { code: '217', region: 'Illinois (Springfield, Champaign)' },
    { code: '218', region: 'Minnesota (Duluth, Moorhead)' },
    { code: '219', region: 'Indiana (Hammond, Gary)' },
    { code: '224', region: 'Illinois (Elgin, Waukegan)' },
    { code: '225', region: 'Louisiana (Baton Rouge)' },
    { code: '228', region: 'Mississippi (Gulfport, Biloxi)' },
    { code: '229', region: 'Georgia (Albany, Valdosta)' },
    { code: '231', region: 'Michigan (Muskegon, Traverse City)' },
    { code: '234', region: 'Ohio (Akron, Canton, Youngstown)' },
    { code: '239', region: 'Florida (Cape Coral, Fort Myers)' },
    { code: '240', region: 'Maryland (Germantown, Silver Spring)' },
    { code: '248', region: 'Michigan (Troy, Pontiac)' },
    { code: '251', region: 'Alabama (Mobile)' },
    { code: '252', region: 'North Carolina (Greenville, Rocky Mount)' },
    { code: '253', region: 'Washington (Tacoma, Auburn)' },
    { code: '254', region: 'Texas (Killeen, Waco)' },
    { code: '256', region: 'Alabama (Huntsville, Decatur)' },
    { code: '260', region: 'Indiana (Fort Wayne)' },
    { code: '262', region: 'Wisconsin (Kenosha, Racine)' },
    { code: '267', region: 'Pennsylvania (Philadelphia)' },
    { code: '269', region: 'Michigan (Kalamazoo, Battle Creek)' },
    { code: '270', region: 'Kentucky (Bowling Green, Owensboro)' },
    { code: '272', region: 'Pennsylvania (Scranton, Wilkes-Barre)' },
    { code: '276', region: 'Virginia (Bristol, Martinsville)' },
    { code: '281', region: 'Texas (Houston)' },
    { code: '301', region: 'Maryland (Germantown, Silver Spring)' },
    { code: '302', region: 'Delaware (Whole State)' },
    { code: '303', region: 'Colorado (Denver, Aurora)' },
    { code: '304', region: 'West Virginia (Whole State)' },
    { code: '305', region: 'Florida (Miami)' },
    { code: '307', region: 'Wyoming (Whole State)' },
    { code: '308', region: 'Nebraska (Grand Island, Kearney)' },
    { code: '309', region: 'Illinois (Peoria, Bloomington)' },
    { code: '310', region: 'California (Los Angeles, Torrance)' },
    { code: '312', region: 'Illinois (Chicago - Central)' },
    { code: '313', region: 'Michigan (Detroit, Dearborn)' },
    { code: '314', region: 'Missouri (St. Louis)' },
    { code: '315', region: 'New York (Syracuse, Utica)' },
    { code: '316', region: 'Kansas (Wichita)' },
    { code: '317', region: 'Indiana (Indianapolis)' },
    { code: '318', region: 'Louisiana (Shreveport, Monroe)' },
    { code: '319', region: 'Iowa (Cedar Rapids, Waterloo)' },
    { code: '320', region: 'Minnesota (St. Cloud)' },
    { code: '321', region: 'Florida (Orlando, Melbourne)' },
    { code: '323', region: 'California (Los Angeles)' },
    { code: '325', region: 'Texas (Abilene, San Angelo)' },
    { code: '330', region: 'Ohio (Akron, Canton, Youngstown)' },
    { code: '331', region: 'Illinois (Aurora, Naperville)' },
    { code: '334', region: 'Alabama (Montgomery, Auburn)' },
    { code: '336', region: 'North Carolina (Greensboro, Winston-Salem)' },
    { code: '337', region: 'Louisiana (Lafayette, Lake Charles)' },
    { code: '339', region: 'Massachusetts (Cambridge, Lynn)' },
    { code: '346', region: 'Texas (Houston)' },
    { code: '347', region: 'New York (New York City)' },
    { code: '351', region: 'Massachusetts (Lowell, Lawrence)' },
    { code: '352', region: 'Florida (Gainesville, Ocala)' },
    { code: '360', region: 'Washington (Vancouver, Bellingham)' },
    { code: '361', region: 'Texas (Corpus Christi, Victoria)' },
    { code: '364', region: 'Kentucky (Paducah, Bowling Green)' },
    { code: '385', region: 'Utah (Salt Lake City)' },
    { code: '386', region: 'Florida (Palm Coast, Daytona Beach)' },
    { code: '401', region: 'Rhode Island (Whole State)' },
    { code: '402', region: 'Nebraska (Omaha, Lincoln)' },
    { code: '404', region: 'Georgia (Atlanta)' },
    { code: '405', region: 'Oklahoma (Oklahoma City)' },
    { code: '406', region: 'Montana (Whole State)' },
    { code: '407', region: 'Florida (Orlando, Kissimmee)' },
    { code: '408', region: 'California (San Jose)' },
    { code: '409', region: 'Texas (Beaumont, Galveston)' },
    { code: '410', region: 'Maryland (Baltimore)' },
    { code: '412', region: 'Pennsylvania (Pittsburgh)' },
    { code: '413', region: 'Massachusetts (Springfield, Pittsfield)' },
    { code: '414', region: 'Wisconsin (Milwaukee)' },
    { code: '415', region: 'California (San Francisco)' },
    { code: '417', region: 'Missouri await (Springfield, Joplin)' },
    { code: '419', region: 'Ohio (Toledo, Mansfield)' },
    { code: '423', region: 'Tennessee (Chattanooga, Knoxville)' },
    { code: '424', region: 'California (Los Angeles)' },
    { code: '425', region: 'Washington (Bellevue, Everett)' },
    { code: '430', region: 'Texas (Tyler, Longview)' },
    { code: '432', region: 'Texas (Midland, Odessa)' },
    { code: '434', region: 'Virginia (Lynchburg, Danville)' },
    { code: '435', region: 'Utah (St. George, Logan)' },
    { code: '440', region: 'Ohio (Parma, Lorain)' },
    { code: '442', region: 'California (Oceanside, Escondido)' },
    { code: '443', region: 'Maryland (Baltimore)' },
    { code: '445', region: 'Pennsylvania (Philadelphia)' },
    { code: '458', region: 'Oregon (Eugene, Bend)' },
    { code: '469', region: 'Texas (Dallas, Plano)' },
    { code: '470', region: 'Georgia (Atlanta)' },
    { code: '475', region: 'Connecticut (Bridgeport, New Haven)' },
    { code: '478', region: 'Georgia (Macon, Warner Robins)' },
    { code: '479', region: 'Arkansas (Fort Smith, Fayetteville)' },
    { code: '480', region: 'Arizona (Mesa, Scottsdale)' },
    { code: '484', region: 'Pennsylvania (Allentown, Reading)' },
    { code: '501', region: 'Arkansas (Little Rock)' },
    { code: '502', region: 'Kentucky (Louisville)' },
    { code: '503', region: 'Oregon (Portland)' },
    { code: '504', region: 'Louisiana (New Orleans)' },
    { code: '505', region: 'New Mexico (Albuquerque)' },
    { code: '507', region: 'Minnesota (Rochester, Mankato)' },
    { code: '508', region: 'Massachusetts (Worcester, New Bedford)' },
    { code: '509', region: 'Washington (Spokane, Yakima)' },
    { code: '510', region: 'California (Oakland, Fremont)' },
    { code: '512', region: 'Texas (Austin)' },
    { code: '513', region: 'Ohio (Cincinnati)' },
    { code: '515', region: 'Iowa (Des Moines)' },
    { code: '516', region: 'New York (Hempstead)' },
    { code: '517', region: 'Michigan (Lansing)' },
    { code: '518', region: 'New York (Albany, Schenectady)' },
    { code: '520', region: 'Arizona (Tucson)' },
    { code: '530', region: 'California (Redding, Chico)' },
    { code: '531', region: 'Nebraska (Omaha, Lincoln)' },
    { code: '534', region: 'Wisconsin (Eau Claire)' },
    { code: '539', region: 'Oklahoma (Tulsa)' },
    { code: '540', region: 'Virginia (Roanoke, Harrisonburg)' },
    { code: '541', region: 'Oregon (Eugene, Bend)' },
    { code: '551', region: 'New Jersey (Jersey City, Hackensack)' },
    { code: '559', region: 'California (Fresno)' },
    { code: '561', region: 'Florida (West Palm Beach, Boca Raton)' },
    { code: '562', region: 'California (Long Beach, Whittier)' },
    { code: '563', region: 'Iowa (Davenport, Dubuque)' },
    { code: '567', region: 'Ohio (Toledo, Mansfield)' },
    { code: '570', region: 'Pennsylvania (Scranton, Wilkes-Barre)' },
    { code: '571', region: 'Virginia (Arlington, Alexandria)' },
    { code: '573', region: 'Missouri (Columbia, Jefferson City)' },
    { code: '574', region: 'Indiana (South Bend, Elkhart)' },
    { code: '575', region: 'New Mexico (Las Cruces, Roswell)' },
    { code: '580', region: 'Oklahoma (Lawton, Enid)' },
    { code: '585', region: 'New York (Rochester)' },
    { code: '586', region: 'Michigan (Warren, Sterling Heights)' },
    { code: '601', region: 'Mississippi (Jackson)' },
    { code: '602', region: 'Arizona (Phoenix)' },
    { code: '603', region: 'New Hampshire (Whole State)' },
    { code: '605', region: 'South Dakota (Whole State)' },
    { code: '606', region: 'Kentucky (Ashland)' },
    { code: '607', region: 'New York (Binghamton)' },
    { code: '608', region: 'Wisconsin (Madison)' },
    { code: '609', region: 'New Jersey (Trenton, Atlantic City)' },
    { code: '610', region: 'Pennsylvania (Allentown, Reading)' },
    { code: '612', region: 'Minnesota (Minneapolis)' },
    { code: '614', region: 'Ohio (Columbus)' },
    { code: '615', region: 'Tennessee (Nashville)' },
    { code: '616', region: 'Michigan (Grand Rapids)' },
    { code: '617', region: 'Massachusetts (Boston)' },
    { code: '618', region: 'Illinois (Belleville, Granite City)' },
    { code: '619', region: 'California (San Diego)' },
    { code: '620', region: 'Kansas (Hutchinson)' },
    { code: '623', region: 'Arizona (Phoenix, Peoria)' },
    { code: '626', region: 'California (Pasadena, El Monte)' },
    { code: '629', region: 'Tennessee (Nashville)' },
    { code: '630', region: 'Illinois (Aurora, Naperville)' },
    { code: '631', region: 'New York (Brentwood)' },
    { code: '636', region: 'Missouri (O\'Fallon, St. Charles)' },
    { code: '641', region: 'Iowa await (Mason City)' },
    { code: '646', region: 'New York (Manhattan)' },
    { code: '650', region: 'California (San Mateo, Redwood City)' },
    { code: '651', region: 'Minnesota (St. Paul)' },
    { code: '657', region: 'California (Anaheim, Santa Ana)' },
    { code: '660', region: 'Missouri (Sedalia)' },
    { code: '661', region: 'California (Santa Clarita, Lancaster)' },
    { code: '662', region: 'Mississippi (Southaven, Tupelo)' },
    { code: '667', region: 'Maryland (Baltimore)' },
    { code: '669', region: 'California (San Jose)' },
    { code: '678', region: 'Georgia (Atlanta)' },
    { code: '682', region: 'Texas (Fort Worth, Arlington)' },
    { code: '701', region: 'North Dakota (Whole State)' },
    { code: '702', region: 'Nevada (Las Vegas)' },
    { code: '703', region: 'Virginia (Arlington, Alexandria)' },
    { code: '704', region: 'North Carolina (Charlotte)' },
    { code: '706', region: 'Georgia (Augusta, Columbus)' },
    { code: '707', region: 'California (Santa Rosa, Vallejo)' },
    { code: '708', region: 'Illinois (Cicero, Orland Park)' },
    { code: '712', region: 'Iowa (Sioux City, Council Bluffs)' },
    { code: '713', region: 'Texas (Houston)' },
    { code: '714', region: 'California (Anaheim, Santa Ana)' },
    { code: '715', region: 'Wisconsin (Eau Claire)' },
    { code: '716', region: 'New York (Buffalo)' },
    { code: '717', region: 'Pennsylvania (Lancaster, Harrisburg)' },
    { code: '718', region: 'New York (New York City)' },
    { code: '719', region: 'Colorado (Colorado Springs, Pueblo)' },
    { code: '720', region: 'Colorado (Denver, Aurora)' },
    { code: '724', region: 'Pennsylvania (New Castle)' },
    { code: '727', region: 'Florida (St. Petersburg, Clearwater)' },
    { code: '731', region: 'Tennessee (Jackson)' },
    { code: '732', region: 'New Jersey (Toms River, New Brunswick)' },
    { code: '734', region: 'Michigan (Ann Arbor, Livonia)' },
    { code: '737', region: 'Texas (Austin)' },
    { code: '740', region: 'Ohio (Newark)' },
    { code: '747', region: 'California (Los Angeles - San Fernando Valley)' },
    { code: '754', region: 'Florida (Fort Lauderdale, Pembroke Pines)' },
    { code: '757', region: 'Virginia (Virginia Beach, Norfolk)' },
    { code: '760', region: 'California (Oceanside, Escondido)' },
    { code: '762', region: 'Georgia (Augusta, Columbus)' },
    { code: '763', region: 'Minnesota (Brooklyn Park, Plymouth)' },
    { code: '765', region: 'Indiana (Muncie, Lafayette)' },
    { code: '769', region: 'Mississippi (Jackson)' },
    { code: '770', region: 'Georgia (Roswell, Johns Creek)' },
    { code: '772', region: 'Florida (Port St. Lucie)' },
    { code: '773', region: 'Illinois (Chicago)' },
    { code: '774', region: 'Massachusetts (Worcester, New Bedford)' },
    { code: '775', region: 'Nevada (Reno, Sparks)' },
    { code: '779', region: 'Illinois (Rockford, Joliet)' },
    { code: '781', region: 'Massachusetts (Lynn, Waltham)' },
    { code: '785', region: 'Kansas (Topeka, Lawrence)' },
    { code: '786', region: 'Florida (Miami)' },
    { code: '787', region: 'Puerto Rico (San Juan, Bayamon)' },
    { code: '801', region: 'Utah (Salt Lake City)' },
    { code: '802', region: 'Vermont (Whole State)' },
    { code: '803', region: 'South Carolina (Columbia, Rock Hill)' },
    { code: '804', region: 'Virginia (Richmond)' },
    { code: '805', region: 'California (Oxnard, Thousand Oaks)' },
    { code: '806', region: 'Texas (Lubbock, Amarillo)' },
    { code: '808', region: 'Hawaii (Whole State)' },
    { code: '810', region: 'Michigan (Flint)' },
    { code: '812', region: 'Indiana (Evansville)' },
    { code: '813', region: 'Florida (Tampa)' },
    { code: '814', region: 'Pennsylvania (Erie, Altoona)' },
    { code: '815', region: 'Illinois (Rockford, Joliet)' },
    { code: '816', region: 'Missouri (Kansas City)' },
    { code: '817', region: 'Texas (Fort Worth, Arlington)' },
    { code: '818', region: 'California (Los Angeles - San Fernando Valley)' },
    { code: '828', region: 'North Carolina (Asheville)' },
    { code: '830', region: 'Texas (New Braunfels)' },
    { code: '831', region: 'California (Salinas, Santa Cruz)' },
    { code: '832', region: 'Texas (Houston)' },
    { code: '843', region: 'South Carolina (Charleston, North Charleston)' },
    { code: '845', region: 'New York (Clarkstown, Ramapo)' },
    { code: '847', region: 'Illinois (Elgin, Waukegan)' },
    { code: '848', region: 'New Jersey (Toms River, New Brunswick)' },
    { code: '850', region: 'Florida (Tallahassee)' },
    { code: '856', region: 'New Jersey (Camden, Cherry Hill)' },
    { code: '857', region: 'Massachusetts (Boston)' },
    { code: '858', region: 'California (San Diego)' },
    { code: '859', region: 'Kentucky (Lexington-Fayette)' },
    { code: '860', region: 'Connecticut (Hartford, New Britain)' },
    { code: '862', region: 'New Jersey (Newark, Jersey City)' },
    { code: '863', region: 'Florida (Lakeland)' },
    { code: '864', region: 'South Carolina (Greenville)' },
    { code: '865', region: 'Tennessee (Knoxville)' },
    { code: '870', region: 'Arkansas (Jonesboro, Pine Bluff)' },
    { code: '872', region: 'Illinois (Chicago)' },
    { code: '878', region: 'Pennsylvania (Pittsburgh, New Castle)' },
    { code: '901', region: 'Tennessee (Memphis)' },
    { code: '903', region: 'Texas (Tyler, Longview)' },
    { code: '904', region: 'Florida (Jacksonville)' },
    { code: '906', region: 'Michigan (Marquette)' },
    { code: '907', region: 'Alaska (Whole State)' },
    { code: '908', region: 'New Jersey (Elizabeth, Plainfield)' },
    { code: '909', region: 'California (San Bernardino, Fontana)' },
    { code: '910', region: 'North Carolina (Fayetteville, Wilmington)' },
    { code: '912', region: 'Georgia (Savannah)' },
    { code: '913', region: 'Kansas (Overland Park, Kansas City)' },
    { code: '914', region: 'New York (Yonkers, New Rochelle)' },
    { code: '915', region: 'Texas (El Paso)' },
    { code: '916', region: 'California (Sacramento)' },
    { code: '917', region: 'New York (New York City)' },
    { code: '918', region: 'Oklahoma (Tulsa, Broken Arrow)' },
    { code: '919', region: 'North Carolina (Raleigh, Durham)' },
    { code: '920', region: 'Wisconsin (Green Bay, Appleton)' },
    { code: '925', region: 'California (Concord, Antioch)' },
    { code: '928', region: 'Arizona (Yuma, Flagstaff)' },
    { code: '931', region: 'Tennessee (Clarksville)' },
    { code: '934', region: 'New York (Brentwood)' },
    { code: '936', region: 'Texas (Huntsville)' },
    { code: '937', region: 'Ohio (Dayton)' },
    { code: '938', region: 'Alabama (Huntsville, Decatur)' },
    { code: '939', region: 'Puerto Rico (San Juan)' },
    { code: '940', region: 'Texas (Denton, Wichita Falls)' },
    { code: '941', region: 'Florida (North Port, Sarasota)' },
    { code: '947', region: 'Michigan (Troy, Pontiac)' },
    { code: '949', region: 'California (Irvine, Newport Beach)' },
    { code: '951', region: 'California (Riverside, Moreno Valley)' },
    { code: '952', region: 'Minnesota (Bloomington)' },
    { code: '954', region: 'Florida (Fort Lauderdale, Pembroke Pines)' },
    { code: '956', region: 'Texas (Laredo, Brownsville)' },
    { code: '959', region: 'Connecticut (Hartford, New Britain)' },
    { code: '970', region: 'Colorado (Fort Collins, Greeley)' },
    { code: '971', region: 'Oregon (Portland)' },
    { code: '972', region: 'Texas (Dallas, Plano)' },
    { code: '973', region: 'New Jersey (Newark, Paterson)' },
    { code: '978', region: 'Massachusetts (Lowell, Lawrence)' },
    { code: '979', region: 'Texas (College Station, Bryan)' },
    { code: '980', region: 'North Carolina (Charlotte)' },
    { code: '984', region: 'North Carolina (Raleigh, Durham)' },
    { code: '985', region: 'Louisiana (Houma)' },
    { code: '986', region: 'Idaho (Whole State)' },
    { code: '989', region: 'Michigan (Saginaw, Midland)' }
];
